vaadin/testbench

- testbench-integration-tests/src/main/java/com/vaadin/testUI/CheckBoxGroupSetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/OptionGroupSetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/RadioButtonGroupSetValue.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/checkboxgroup/CheckBoxGroupSetValueIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/radiobuttongroup/RadioButtonGroupSetValueIT.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CalendarElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/FormElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/PopupDateFieldElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/ProgressIndicatorElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/SelectElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableHeaderElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableRowElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TreeElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TreeTableElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TreeTableRowElement.java
Added RadioButtonGroupElement and CheckBoxGroupElement
Deprecated elements for deprectated components in framework
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/817)
> Update element API for components in FW8

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBench.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/TestBenchElementTest.java
Fixes #778
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/819)
> Return null when wrapping a null element

- documentation/testbench-tutorial.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/822)
> Always use same name for AddressBookIT test

- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/twincolselect/TwinColSelectUIIT.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TwinColSelectElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/825)
> Add API to getAvailableOptions in TwinColSelectElement

- pom.xml
- testbench-integration-tests/pom.xml
- vaadin-testbench-api/pom.xml
- vaadin-testbench-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/820)
> Fix Maven project warnings

- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityAbstractFieldElementSetValueReadOnly.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityAbstractTextElementSetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityComponentElementGetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityElementComponentGetCaptionBase.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityElementComponentGetCaptionCssLayout.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityElementComponentGetCaptionFormLayout.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityElementComponentGetCaptionGridLayout.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityElementComponentGetCaptionHorizontal.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CompatibilityElementComponentGetCaptionVerticalLayout.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementComponentGetCaptionBase.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/CompatibilityComponentElementGetValueIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/CompatibilityElementComponentGetCaptionBaseIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/CompatibilityElementComponentGetCaptionCssLayoutIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/CompatibilityElementComponentGetCaptionFormLayoutIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/CompatibilityElementComponentGetCaptionGridLayoutIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/CompatibilityElementComponentGetCaptionHorizontalIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/CompatibilityElementComponentGetCaptionVerticalLayoutIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/abstracttextfield/CompatibilityAbstractFieldElementSetValueReadOnlyIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/abstracttextfield/CompatibilityAbstractTextElementSetValueIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/823)
> Add missing tests for compatibility components

- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSplitPanelElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/HorizontalSplitPanelElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/NativeSelectElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TabSheetElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableRowElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/VerticalSplitPanelElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/814)
> Fix visibility of TestBenchElement methods and remove extra methods

- testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxInputNotAllowed.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxInputNotAllowedIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/ComboBoxUIIT.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java
Fixes #758
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/829)
> Make it possible to selectByText in ComboBoxes with text input disabled

- doc/releasenotes.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/831)
> Update release notes for 4.2.0.rc1

- pom.xml
- testbench-integration-tests/src/main/java/com/vaadin/testUI/AbstractFieldElementSetValueReadOnly.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/CheckBoxGroupSetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/ComponentElementGetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/GridUI.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/NativeSelectSetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/RadioButtonGroupSetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/SelectByText.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/TwinColSelectUI.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/830)
> Update FW to 8.0.0.alpha7

- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/optiongroup/OptionGroupSetValueIT.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxGroupElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/OptionGroupElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/RadioButtonGroupElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
Fixes selectByText for OptionGroupElement, CheckBoxGroupElement and RadioButtonGroupElement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/837)
> Fix issue in *GroupElement when selecting by text in chrome

- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/SelectByTextIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/843)
> Make ComboBox tests assert that a value change actually took place

- doc/releasenotes.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/844)
> Update release notes for 5.0.0.alpha1

- documentation/chapter-testbench.asciidoc
- documentation/testbench-migration.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/845)
> Add migration guide for testbench 5

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/826)
> Use 7.7.4 instead of snapshot

- pom.xml
- testbench-integration-tests/pom.xml
- vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/847)
> Use https in sonatype url parameters

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/848)
> Take UnsupportedCommandException into account for element screenshots

- pom.xml
- testbench-integration-tests/src/main/java/com/vaadin/testUI/ComboBoxGetSuggestions.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/ComponentElementGetValue.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/GridUI.java
- testbench-integration-tests/src/main/java/com/vaadin/testUI/SelectByText.java
- vaadin-testbench-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/851)
> Update to vaadin8.alpha8

- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/850)
> Update old reference of selenium version

- doc/releasenotes.html
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/table/GetRowHeaderIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/table/TableScrollIT.java
- testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/tabsheet/PanelScrollIT.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/AbstractSplitPanelElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/CheckBoxElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/HorizontalSplitPanelElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/NativeSelectElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TabSheetElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableRowElement.java
- vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/VerticalSplitPanelElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasTestBenchCommandExecutor.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchDriverProxy.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/846)
> Remove TestBench from method name

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/854)
> Update to framework version 7.7.6

- pom.xml
- testbench-integration-tests/src/main/java/com/vaadin/testUI/NativeSelectSetValue.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/855)
> Update to 8.0.0.alpha9

- documentation/testbench-known-issues.asciidoc
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/Parameters.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/RetryRule.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/ParentRetryRuleTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleAfterTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleBeforeTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleTestbenchTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleTestbenchWithParameterTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/testutils/ParentRetryRule.java
RetryTestRunner allows to run tests several times.
If tests passes at least once it is mared as passed.
That can be useful to prevent random failures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/852)
> Add RetryTestRunner

- documentation/creatingtests/testbench-testcase.asciidoc
- documentation/setup/testbench-installation.asciidoc
- documentation/testbench-overview.asciidoc
- documentation/testbench-quickstart.asciidoc
- documentation/testbench-tutorial.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/857)
> Add info about GeckoDriver setup

- documentation/environment/testbench-maven.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/859)
> Fix duplicated anchors

- documentation/environment/testbench-grid.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/860)
> Remove class names from inside code blocks

- documentation/setup/testbench-installation.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/861)
> Remove stray endif

- pom.xml
- vaadin-testbench-standalone/pom.xml
- vaadin-testbench/pom.xml
Add prerelease repository for testbench-api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/870)
> Update to 5.0.0.beta2

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/873)
> Update to vaadin 8.0.0

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/RetryRule.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/874)
> A test for which an assumption fails should not generate a failure

- documentation/testbench-known-issues.asciidoc
- documentation/testbench-quickstart.asciidoc
- documentation/testbench-tutorial.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/876)
> Add docs about Firefox ESR and GeckoDriver

- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/tools/CvalChecker.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/880)
> Sync license checker with the framework project

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ReferenceNameGenerator.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/screenshot/ReferenceNameGeneratorTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/885)
> Fix NPE when platform is unknown

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/882)
> Make it possible to override getDriver()

- README.md
- vaadin-testbench-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/888)
> updated phantomjs version

- pom.xml
- vaadin-testbench-assembly/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
- vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/892)
> Update to 5.1-SNAPSHOT

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/BrowserUtil.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelRunner.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/BrowserUtilTest.java
Fixes NPE when using ComboBoxElement with JBrowserDriver
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/893)
> Take into account that TestBenchElement.getCapabilities() can return null

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/896)
> Allow nulling the driver after a test

- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/897)
> Fix invalid main class name in manifest

- .gitignore
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommands.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ScrollIntoView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ScrollIntoViewIT.java
Fixes #895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/911)
> Automatically scroll elements into view before interacting with them

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/912)
> Only scrollIntoView elements that are not displayed

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB3Test.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/917)
> Add waitUntil helper method for Element and TestCase

- pom.xml
- vaadin-testbench-assembly/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
- vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/921)
> Change version to 6.0-SNAPSHOT

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/AbstractHasTestBenchCommandExecutor.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasElementQuery.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/924)
> Add HasElementQuery to be able to create lookup interfaces with default methods

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/934)
> Update Vaadin Version

- documentation/creatingtests/testbench-special.asciidoc
Implementation of waitUntil: https://github.com/vaadin/testbench/commit/cde4d3341cdc47f3dee3d02e575e1f86e89ff4ec
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/940)
> Updated doc with waitUntil

- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/943)
> TestBenchElement.getPropertyInteger method added

- documentation/creatingtests/testbench-special.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/941)
> Documented the new helper for waiting on a condition

- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchDriverProxy.java
- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench/src/test/java/com/vaadin/testbench/TestBenchDriverTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/937)
> Fix infinite loop in wait for first

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchDriverProxy.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/TestBenchDriverTest.java
Fixes #945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/950)
> Avoid an infinite loop when trying to find the innermost driver (#949)

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/955)
> Ensure TestBenchElement uses the proxy of the driver

- vaadin-testbench/src/main/java/com/vaadin/testbench/ElementQuery.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/951)
> Fix javadoc to use correct exception type

- vaadin-testbench/src/main/java/com/vaadin/testbench/ElementQuery.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/952)
> Use builder for creating the JS snippet for better formatting

- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/948)
> Test for infinite loop problem

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/957)
> Fix distribution management repo url

- pom.xml
- vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/958)
> Don't repeat distribution management repo

- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
- vaadin-testbench/src/main/resources/com/vaadin/testbench/testbench.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/961)
> Add a runtime check that the expected Selenium version is found

- vaadin-testbench-integration-tests/build-tools/move-build-to-webapp.js
- vaadin-testbench-integration-tests/build-tools/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/967)
> Remove unneeded dependency

- vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/968)
> Remove dependency on GWT user

- vaadin-testbench/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
- vaadin-testbench/src/test/java/com/vaadin/testbench/commands/TestBenchCommandExecutorTest.java
https://github.com/vaadin/flow/issues/3119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/971)
> Add support for new Vaadin client namespace.

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/976)
> Fix problem with sauce-connect repository no longer working

- vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/977)
> Use newest license checker

- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/974)
> Extend property getters to support a chain of property names

- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchElement.java
Depends on #974
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/975)
> Support getting properties containing one or several elements

- vaadin-testbench/src/main/java/com/vaadin/testbench/HasCallFunction.java
- vaadin-testbench/src/main/java/com/vaadin/testbench/HasPropertySettersGetters.java
- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/978)
> Extract TestBenchElement methods to interfaces to be able to make helper interfaces

- vaadin-testbench/src/main/java/com/vaadin/testbench/HasStringValueProperty.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/979)
> Add helper for integrating elements with a string value

- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
- vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/980)
> Add hasAttribute helper

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/985)
> Allow TestBenchElement to be used in ElementQuery to match any element

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasElementQuery.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/986)
> Support finding elements with a given tag name without an element class

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBench.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/984)
> Report exceptions if they happen

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/988)
> Add support for firing custom events

- documentation/testbench-overview.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/991)
> FFS and update for TestBench 6

- documentation/testbench-quickstart.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/992)
> FFS quickstart and update for TestBench 6

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/ElementQueryTest.java
- vaadin-testbench-integration-tests/src/main/webapp/frontend/polymer-template-view.html
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/996)
> Support special characters in attribute values

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/998)
> Throw ISE instead of NPE when context is null

- vaadin-testbench-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1002)
> License checker update

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/annotations/Attribute.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/internal/SharedUtil.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/ElementQueryTest.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/MyComponentWithClasses.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/MyComponentWithId.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PageObjectView.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PolymerTemplateView.java
- vaadin-testbench-integration-tests/src/main/webapp/frontend/polymer-template-view.html
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/MyComponentWithClassesElement.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/MyComponentWithIdElement.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PageObjectIT.java
Also add support finding elements based on attribute tokens like a single class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1000)
> Add @Attribute for defining additional constraints on element classes

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/999)
> Remove unused parameters and fix javadoc

- doc/upgrade-selenium.sh
- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1007)
> Fix remaining old version number

- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ElementScreenCompareIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1010)
> Only resize test window when needed

- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/MyComponentWithClasses.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/MyComponentWithId.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PageObjectView.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PolymerTemplateView.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/SVGView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PageObjectIT.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/SVGIT.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ExecuteJavascriptIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1011)
> Update to Flow beta1

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/commands/TestBenchCommandExecutorTest.java
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/PerformanceView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PerfomanceIT.java
Update Flow beta2 which contains poll() implementation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1012)
> Fix performance testing methods

- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PerfomanceIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1021)
> Increase performance test thresholds to avoid test failures

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1020)
> Add gitter button to readme

- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1026)
> Make test pass on all browsers

- vaadin-testbench-assembly/MANIFEST.MF
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1027)
> Add Implementation-Vendor

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1031)
> Fix another cyclic reference issue

- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ExecuteJavascriptIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1035)
> Rename method to make more sense

- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/AbstractTB6Test.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ElementScreenCompareIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1034)
> Run tests on Safari

- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
It was only used to parse the tunnel ID
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1038)
> Remove ci-sauce dependency

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1039)
> Remove extra dependency from IT module

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/CyclicObjectWorkaround.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/resources/com/vaadin/testbench/cyclic-object-workaround.js
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1036)
> Apply cyclic object workaround to getProperty also

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java
Keep deprecated PLATFORM for Firefox capabilities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1043)
> Fix usage of deprecated DesiredCapabilities methods

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/Parameters.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelRunner.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/DefaultBrowserConfigurationTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/JobNameCapabilitiesTest.java
Allows more descriptive output in Sauce Labs dashboard
before: 
after: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1044)
> Set job name for sauce

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1047)
> Added Vaadin Directory status badge

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1052)
> Use latest flow for IT

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1055)
> Use latest flow

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1068)
> Skip sauce tests also if user and access key are empty

- vaadin-testbench-bom/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1070)
> Fix scope in bom and use bom in modules

- vaadin-testbench-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1075)
> Upgrade license-checker to 1.0.0.alpha6

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1076)
> Update to latest flow

- vaadin-testbench-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1079)
> Correct license-checker final

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1082)
> Increase snapshot version

- vaadin-testbench-assembly/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
- vaadin-testbench/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1083)
> Update to 5.2-SNAPSHOT

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1085)
> Update flow to rc2

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1086)
> Update to flow rc4

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1087)
> Prepare for 6.0.0 final release

- pom.xml
- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1090)
> Use vaadin parent

- pom.xml
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1091)
> Update skip staging

- pom.xml
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1092)
> Skip modules for staging with release profile

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1093)
> Remove profile

- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1094)
> Add skip for staging to IT and standalone

- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1102)
> Remove extra repositories

- vaadin-testbench-api/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1109)
> Also update TB core for TB api

- doc/releasenotes.html
- documentation/testbench-known-issues.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1112)
> Add notes about java support

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/Parameters.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/RetryRule.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/ParentRetryRuleTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleAfterTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleBeforeTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleTestbenchTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/RetryRuleTestbenchWithParameterTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/testutils/ParentRetryRule.java
Picked from #852 and #874
Fixes #1113
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1114)
> Backport support for RetryRule to TB 4.3

- documentation/testbench-quickstart.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1127)
> Update archetype version to 8.6.x

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
This can be used to dispatch events that bubble
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1134)
> Add api to dispatchEvent with initialization info

- documentation/testbench-ci-server.asciidoc
Fixes #1135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1137)
> Fix invalid link

- documentation/environment/testbench-maven.asciidoc
Part 1 out of 2 for #1136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1138)
> Fix broken link in docs

- documentation/environment/testbench-maven.asciidoc
Part 2 out of 2 for #1136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1140)
> Fix broken link in docs (#1139)

- pom.xml
- vaadin-testbench-container/vaadin-testbench-container-test/pom.xml
- vaadin-testbench-it/vaadin-testbench-it-test/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1170)
> Check license headers

- pom.xml
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-meecrowave/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/MeecrowaveContainerInitializer.java
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-none/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/NoContainerInitializer.java
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-springboot/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/AbstractSpringBootContainerInitializer.java
- vaadin-testbench-container/vaadin-testbench-container-test/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchLogger.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/ConvertWebdriverTestExtension.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/ExtensionFunctions.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/ContainerInfoExtension.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/ContainerInitializer.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/NetworkFunctions.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/ServletContainerExtension.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/PageObjectWebDriverCleanerExtension.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/WebDriverTemplateInvocationContextImpl.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/BrowserDriverFunctions.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/conf/WebdriversConfig.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/conf/WebdriversConfigFactory.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ImageComparison.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ImageFileUtil.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ScreenShotFailureReporter.java
- vaadin-testbench-it/pom.xml
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/upload/UploadIT.java
Fixes #1164 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1173)
> Enable log messages

- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-springboot/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/SpringBootConf.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/VaadinTest.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/SkipBrowsers.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/annotations/Element.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/combobox/ComboBoxIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/common/AbstractIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/datepicker/DatePickerIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/dialog/DialogIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/formlayout/FormLayoutIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/grid/GridIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/ironlist/IronListIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/notification/NotificationIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/orderedlayout/HorizontalLayoutIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/orderedlayout/VerticalLayoutIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/progressbar/ProgressBarIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/radiobutton/RadioButtonIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/splitlayout/SplitLayoutIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/tabs/TabsIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/textfield/PasswordFieldIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/textfield/TextAreaIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/textfield/TextFieldIT.java
- vaadin-testbench-it/vaadin-testbench-it-test/src/test/java/com/vaadin/testbench/tests/component/upload/UploadIT.java
Fixes #1154 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1174)
> Make test annotations inherited

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1180)
> Delete invalid javadoc

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/ElementQueryTest.java
Fixes #1178
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1179)
> Add ElementQuery.hasAttribute

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1186)
> Update sauce config

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasLabel.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasPlaceholder.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasSelectByText.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1187)
> Move common classes from vaadin-components-testbench

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/PageObjectInvocationContextProvider.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/BrowserDriverFunctions.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/BrowserType.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/SkipBrowsers.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/component/grid/GridIT.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/component/tabs/TabsIT.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/component/upload/UploadIT.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/ui/SVGIT.java
- vaadin-testbench-it/src/test/resources/.testbenchextensions/config.properties
Fixes #1193 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1195)
> Find @SkipBrowsers on the test class hierarchy

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/PageObjectInvocationContextProvider.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/VaadinPreloadTargetExtension.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/VaadinTest.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/SkipBrowsers.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/annotations/AnnotationHelper.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/annotations/AnnotationHelperTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1196)
> Extract annotation queries

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/configuration/ConfigurationFinder.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/configuration/ConfigurationFinderTest.java
Fixes #1199 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1200)
> Allow specification of test configuration class via an environment variable

- pom.xml
- vaadin-testbench-bom/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1201)
> Override byte buddy

- pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/junit5/extensions/unittest/WebDriverTemplateInvocationContextImpl.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/addons/webdriver/BrowserDriverFunctions.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/annotations/AnnotationHelperTest.java
Fixes https://github.com/vaadin/pro-team-tasks/issues/10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1202)
> Remove webdriverextensions dependency

- vaadin-testbench-integration-tests/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1205)
> Use latest flow in IT

- vaadin-testbench-it/pom.xml
Fixes #1194 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1208)
> Run failsafe verify goal

- documentation/testbench-own-grid.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1207)
> Fix second changes for book of Vaadin

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/elementsbase/Element.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/ui/element/NativeButtonElement.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/ui/element/PolymerTemplateViewElement.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1210)
> Moved Element annotation back to elementsbase package

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1217)
> update fw version

- pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1218)
> Update developer infor

- documentation/testbench-getting-started.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1216)
> Restructure getting started doc

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ScreenshotOnFailureRule.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1213)
> Log location of screenshot file

- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-meecrowave/src/main/java/com/vaadin/testbench/addons/junit5/extensions/container/MeecrowaveContainerInitializer.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/ui/SVGIT.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/ui/element/ElementScreenCompareIT.java
- vaadin-testbench-it/src/test/java/com/vaadin/testbench/tests/ui/element/ExecuteJavaScriptIT.java
Fixes #1191
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1209)
> Make best effort to support BEFORE_ALL when test class is not annotated

- documentation/testbench-maintainable-tests-using-page-objects.asciidoc
Fix class definition on code samples
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1219)
> Fix code snippets

- doc/maven/INSTALL
Related to vaadin/platform#766
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1221)
> Use https for Maven repositories

- pom.xml
- vaadin-testbench-bom/pom.xml
- vaadin-testbench-container/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-runtime/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-meecrowave/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-none/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-springboot-v01/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-springboot-v02/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-runtime/vaadin-testbench-container-runtime-springboot/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-test/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-test/vaadin-testbench-container-test-meecrowave/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-test/vaadin-testbench-container-test-none/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-test/vaadin-testbench-container-test-springboot-v01/pom.xml
- vaadin-testbench-container/vaadin-testbench-container-test/vaadin-testbench-container-test-springboot-v02/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-it/pom.xml
Fixes vaadin/pro-team-tasks#17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1225)
> Changes to testbench repo (vaadin/pro-team-tasks#17)

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelTest.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1235)
> Do not log a warning for every test which is not run on Saucelabs

- pom.xml
- vaadin-testbench-bom/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1238)
> Prepare for next minor release

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
Fixes #1230
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1231)
> feature: optional timeout for waitForFirst()

- pom.xml
- vaadin-testbench-core/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1252)
> Update to latest parent and LC

- documentation/testbench-overview.asciidoc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1258)
> Update licensing information on TB overview

- pom.xml
- vaadin-testbench-bom/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasHelper.java
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-standalone/pom.xml
Interface to be implemented by field components which has the helper feature.
> feat: add HasHelper interface

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasHelper.java
> fix: checks for "slot" in HasHelper#getHelperComponent

- vaadin-testbench-core/pom.xml
This updates guava to more recent version
> Override outdated guava (transient dep of remote driver)

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-core/src/test/java/com/example/SingleParam.java
- vaadin-testbench-core/src/test/java/com/example/TemplatedParam.java
- vaadin-testbench-core/src/test/java/com/example/base/About.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/UIUnit4BaseClassTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/UIUnitBaseClassTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/UIUnitNavigationTest.java
Add methods for navigating to
different views into the base class.
Fixes #1331
> feat: add navigation methods to base

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentWrap.java
- vaadin-testbench-core/src/test/java/com/example/base/Home.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentWrapTest.java
Add a generic test wrapper for
Components with usability check.
Fixes #1332
> feat: Add generic test ComponentWrap

- vaadin-testbench-core/src/main/kotlin/com/vaadin/testbench/unit/internal/BasicUtils.kt
- vaadin-testbench-core/src/main/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTree.kt
- vaadin-testbench-core/src/test/kotlin/com/vaadin/testbench/unit/internal/AttachedTextField.kt
- vaadin-testbench-core/src/test/kotlin/com/vaadin/testbench/unit/internal/BasicUtilsTest.kt
Fix minor issues in the enabled check
and add is attached to checkEditableByUser.
> Fix: fix enabled check and checkEditableByUser

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/TextFieldWrap.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentWrapTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/TextFieldWrapTest.java
Created test wrapper for TextField and its
derivatives.
Closes #1333
> feat: TextFieldWrap test wrapper for TextField

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentWrap.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/NotificationWrap.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/TextFieldWrap.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentWrapTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/NotificationWrapTest.java
Adds a wrapper for notification with methods to get notification text and
to close a displayed notification.
Fixes #1335
> feat: Added notification wrapper

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/CyclicObjectWorkaround.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ButtonWrap.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/NotificationWrap.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/TextFieldWrap.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/Wraps.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/TestComponent.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/TestWrap.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/TextFieldWrapTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/WrapperResolutionTest.java
> feat: Automatically select matching wrapper

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
Fix the mistake of having `org.apache.commons.collections4.map.HashedMap` instead of `java.util.HashMap`
> chore: use HashMap not HashedMap

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
- vaadin-testbench-core/src/main/kotlin/com/vaadin/testbench/unit/internal/Locator.kt
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
- vaadin-testbench-core/src/test/kotlin/com/vaadin/testbench/unit/internal/LocatorTest.kt
Added possibility to define query to
requre themes or tht they are not available.
Fixes #1375
> feat: Add query by theme

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
Added helper for searching for components with and without CSS classes
applied.
Part of #1370
> feat: Added component query helpers for CSS classes

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
- vaadin-testbench-core/src/main/kotlin/com/vaadin/testbench/unit/internal/Locator.kt
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
Added helpers to search for components with caption matching or containing given test
Part of #1370
> feat: added component query helper for caption

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
Added helper to search for fields with a given value.
Part of #1370
> feat: Added component query helper for field value

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ElementConditions.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ElementConditionsTest.java
Added helper for searching for components with and without attribute
presence and value.
Fixes #1376
> feat: Added component query helpers for attributes

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/accordion/AccordionWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/grid/GridWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/accordion/AccordionView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/accordion/AccordionWrapTest.java
> feat: Add accordion test wrapper

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/combobox/ComboBoxWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/grid/GridWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentWrap.java
- vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/component/Grid.kt
- vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/BasicUtils.kt
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/combobox/ComboBoxView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/combobox/ComboBoxWrapTest.java
> feat: Add ComboBoxWrap

- vaadin-testbench-unit/pom.xml
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/SpringUIUnit4Test.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/SpringUIUnitTest.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/mocks/MockSpringServlet.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/mocks/MockSpringServletService.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/mocks/MockSpringVaadinSession.java
- vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/SpringUIUnit4BaseClassTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/SpringUIUnitBaseClassTest.java
Added JUnit 4 and 5 base test classes that integrates Spring testing
framework and set up a mock Vaadin Spring environment
Fixes #1337
> feat: Added base classes for spring based UI unit tests

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/login/AbstractLoginWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/login/LoginFormWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/login/LoginOverlayWrap.java
- vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTree.kt
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/login/LoginFormView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/login/LoginFormWrapTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/login/LoginOverlayView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/login/LoginOverlayWrapTest.java
> feat: Login component wrappers

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/textfield/TextFieldWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/textfield/TextFieldWrapTest.java
Add validation of the value for
TextFieldWrap if a validation has
been set.
> feat: validate input in TextFieldWrap

- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-unit/src/main/resources/com/vaadin/testbench/unit/testbench.properties
> chore: add LicenseCheck for ui unit

- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
- vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
> feat: Added single terminal opreator to ComponentQuery

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/grid/GridWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/BeanGridView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/BeanGridWrapTest.java
Add methods to get column or
column index by property name.
fixes #1421
> feat: Enable get column by property

- vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTree.kt
- vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTreeTest.kt
> fix: handle null property values in PrettyPrintTree

- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/button/ButtonView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/button/ButtonWrapTest.java
Button test now doesn't depend
on unit module views.
> chore: fix button test

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ReferenceNameGenerator.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/screenshot/ReferenceNameGeneratorTest.java
> fix: Do not use unix name for linux screenshots

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogWrapTest.java
> feat: Test wrap for ConfirmDialog

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/timepicker/TimePickerWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/timepicker/TimePickerView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/timepicker/TimePickerWrapTest.java
> feat: Test wrap TimePicker

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/grid/GridWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/GridWrapSortTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/Person.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/SortGridView.java
> feat: Added helpers for sorting on GridWrap

- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
- vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/Shortcuts.kt
- vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnitShortcutTest.java
- vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/AllTests.kt
- vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/ShortcutsTest.kt
Imported and integrated Karibu shortcuts handling
Fixes #1377
> feat: Added keyboard shortcuts simulation

- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/MetaKeys.java
Make setters fluent for better ux
as per tester feedback
> fix: Make MetaKeys setters fluent.

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/details/DetailsWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/details/DetailsView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/details/DetailsWrapTest.java
> feat: Added wrapper for Details component

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupWrapTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonWrapTest.java
> feat: add RadioButton wrappers

- vaadin-testbench-unit/pom.xml
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/combobox/ComboBoxWrap.java
> chore!: update to 23.2

- vaadin-testbench-unit/pom.xml
remove vaadin-bom from unit module
> fix: remove bom

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroupWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/checkbox/CheckboxWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/login/LoginOverlayWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/notification/NotificationWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/textfield/NumberFieldWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/textfield/TextAreaWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/textfield/TextFieldWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentWrap.java
> chore: improve message for component not usable exception

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/messages/MessageInputWrap.java
- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/messages/MessageListWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/messages/MessageInputWrapTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/messages/MessageListWrapTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/messages/MessagesView.java
> feat: Wrapper for messages

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/grid/GridWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/BasicGridView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/BasicGridWrapTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/CheckBox.java
Add method for getting the component
for a cell in a grid.
Fixes #1467
> feat: add method to get the item component

- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuWrapTest.java
Exception was thrown, but not for the expected reason, but because menu was not open.
> test: fixed wrong test

- vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/menubar/MenuBarWrap.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/menubar/MenuBarView.java
- vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/menubar/MenuBarWrapTest.java
> feat: Added wrapper for MenuBar

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/Parameters.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/Browser.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/BrowserUtil.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/LocalDriver.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/DefaultBrowserConfigurationTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/ParallelRunLocallyTest.java
> fix: Remove Internet Explorer references

- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/ScreenshotOnFailureRule.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ImageFileUtil.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/JobNameCapabilitiesTest.java
Use rebase merge, do not squash
> Cherry picks 6.5

- pom.xml
- vaadin-testbench-bom/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-unit/pom.xml
Version bump - 9.0-SNAPSHOT as master
> chore: Update project version to 9.0-SNAPSHOT

- vaadin-testbench-bom/pom.xml
- vaadin-testbench-core-junit5/pom.xml
- vaadin-testbench-integration-tests-junit5/pom.xml
Added JUnit5 TestBench dependencies to vaadin-testbench-bom
> chore: added junit5 deps to bom

- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/textfield/TextAreaTesterTest.java
- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/textfield/TextFieldTesterTest.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/textfield/TextAreaTester.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/textfield/TextFieldTester.java
- vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/component/Grid.kt
> chore: remove IronList references from testbench

- pom.xml
- vaadin-testbench-core-junit5/pom.xml
- vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/BrowserTestBase.java
- vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/ScreenshotOnFailureExtension.java
- vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/parallel/ParallelConfigurationStrategy.java
- vaadin-testbench-core-junit5/src/main/resources/junit-platform.properties
- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/JobNameCapabilitiesTest.java
- vaadin-testbench-integration-tests-junit5/pom.xml
- vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/AbstractBrowserTB9Test.java
- vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/AbstractSeleniumTB9Test.java
- vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/AbstractTB9Test.java
- vaadin-testbench-integration-tests-junit5/src/test/resources/junit-platform.properties
- vaadin-testbench-integration-tests-junit5/vite.generated.ts
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-shared/pom.xml
- vaadin-testbench-unit-junit5/pom.xml
- vaadin-testbench-unit-shared/pom.xml
- vaadin-testbench-unit/pom.xml
- vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/ComponentTesterTest.java
- vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnit4BaseClassTest.java
Changes after DX tests:
1. Moved parallel configuration to testbench-core-junit5 and enabled by default
2. Added custom parallel configuration to support testbench Parameters
3. Added driver closing on test failure while using screenshot extension
> test: update after dx tests

- vaadin-testbench-bom/pom.xml
- vaadin-testbench-core-junit5/pom.xml
- vaadin-testbench-core/pom.xml
- vaadin-testbench-shared/pom.xml
Also added explicit dependency in modules using selenium-http
Fixes #1577
> chore: added selenium dependencies to BOM

- vaadin-testbench-integration-tests-junit5/src/main/java/com/vaadin/testUI/SVGView.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/SVGView.java
Replaced usage of deprecated API, removed in Flow 24
> chore: replaced deprecated removed API usage

- pom.xml
Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)
> chore: update License-checker to 1.12.0 (8.1)

- pom.xml
Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)
> chore: update License-checker to 1.12.0 (8.2)

- vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/Shortcuts.kt
* As the ShortcutRegistration will always use HashableKeys, hence why we need to use it in our tests as well to not have any differences between our tests and real-life application. (now we used simple Key objects, but we need to use HashableKeys)
* Cleaned up the code a bit to use the HashableKey creation only in the MockFilterJsonObject class. (Based on @mcollovati  review, thank you)
* Put the getHashableKey() method into the class (mock JSON), so where we use it (suggestion by @mcollovati, thanks!).
* One more time, even nicer this way, like this one :) (Thanks again @mcollovati)
* Revert GridTester changes, and fix java doc for the newly added getHashableKey() method, fix imports.
* Using a bit more Kotlinish syntax for reflection (private inner class constructor), and being more …
> fix: changing Shortcuts.kts logic to use HashableKeys. (#1616)(CP: 8.2)

- vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/Shortcuts.kt
* As the ShortcutRegistration will always use HashableKeys, hence why we need to use it in our tests as well to not have any differences between our tests and real-life application. (now we used simple Key objects, but we need to use HashableKeys)
* Cleaned up the code a bit to use the HashableKey creation only in the MockFilterJsonObject class. (Based on @mcollovati  review, thank you)
* Put the getHashableKey() method into the class (mock JSON), so where we use it (suggestion by @mcollovati, thanks!).
* One more time, even nicer this way, like this one :) (Thanks again @mcollovati)
* Revert GridTester changes, and fix java doc for the newly added getHashableKey() method, fix imports.
* Using a bit more Kotlinish syntax for reflection (private inner class constructor), and being more …
> fix: changing Shortcuts.kts logic to use HashableKeys. (#1616) (#1619)

- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
https://docs.saucelabs.com/dev/cli/sauce-connect-proxy/index.html#--tunnel-identifier
Environment variable: SAUCE_TUNNEL_IDENTIFIER
> fix: Sync tunnel id variable with sc proxy

- vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/SVGIT.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/SVGIT.java
> Revert "Ignore test that breaks Saucelabs"

- vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
> fix: Make BaseUIUnitTest extendable

- vaadin-testbench-bom/pom.xml
Fixes https://github.com/vaadin/testbench/issues/1664
> fix: Add Selenium Manager to bom

- vaadin-testbench-bom/pom.xml
probably we should consider to bump the project version
> fix : remove scope from dependencies in bom

- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/html/testbench/NativeLabelTester.java
In Vaadin 24.1 NativeLabel replaced Label
> chore: Add missing NativeLabelTester

- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTesterTest.java
- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxView.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxTester.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java
Part of https://github.com/vaadin/testbench/issues/1635
> feat: Add MultiSelectComboBoxTester

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/RemoteDriver.java
By default remote driver is created with a connection timeout of 2 minutes and a read timeout of 3 hours. This sometimes causes the validation jobs to fail with execution timeout, because the remote driver client hangs because of the 3 hours read timeout.
This change resets the timeout values to be similar to the configuration used by recent selenium versions.
> fix: override remote driver default timeouts

- vaadin-testbench-unit-junit5/pom.xml
- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SecurityTestConfig.java
- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SpringUnitSecurityViewAccessCheckerTest.java
Adds tests for navigation access control integration in UI unit tests
> test: add test for NavigationAccessControl integration

- pom.xml
> upgrade selenium to 4.16.0

- pom.xml
Please list all relevant dependencies in this section and provide summary of the change, motivation and context.
Fixes # (issue)
> Upgrade selenium version to 4.16.0 (9.0)

- pom.xml
4.16.0 contains broken packages, so 4.16.1 is needed
> upgrade to selenium 4.16.1

- vaadin-testbench-integration-tests-junit5/pom.xml
- vaadin-testbench-integration-tests/pom.xml
> update jetty to 11.0.15 (9.1)

- vaadin-testbench-core/pom.xml
- vaadin-testbench-shared/pom.xml
probably needed as https://github.com/vaadin/flow/pull/18923
> chore: bump commons-codec to 1.16.1

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
Fixes https://github.com/vaadin/testbench/issues/869
> fix: Wait for page load complete in waitForVaadin

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/TestBenchElementTest.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementAttributeUI.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ElementAttributeIT.java
> feat: Add TestBenchElement getters for id and read-only state

- vaadin-testbench-core/src/test/java/com/vaadin/testbench/TestBenchElementTest.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java
> feat: Add TestBenchElement#getId

- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/HasValidation.java
> feat: Add HasValidation mixin interface

- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java
> feat: Add TestBenchElement#isReadOnly

- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/HasClearButton.java
Fixes #1902 
This interface should be implemented by TextFieldElement, ComboBoxElement, MultiSelectComboBoxElement, DatePickerElement, ...
> feat: Add HasClearButton mixin interface

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementAttributeUI.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ElementAttributeIT.java
(Also remove an unrelated test sysout that shouldn't have been committed in the first place.)
Based on #1906
> feat: Add a helper method for checking TestBenchElement's focus state

- vaadin-testbench-core/pom.xml
> Remove unused dependency to selenium-server (V8)

- vaadin-testbench-integration-tests-junit5/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java
> feat: Add TestBenchElement#getChildren

- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java
> fix: Override and deprecate getShadowRoot

- .gitignore
- README.md
- doc/license.html
- vaadin-testbench-core/pom.xml
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/annotations/BrowserConfiguration.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/Browser.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/BrowserUtil.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/LocalDriver.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/ParallelRunLocallyTest.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/screenshot/ReferenceNameGeneratorTest.java
- vaadin-testbench-integration-tests/pom.xml
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/MultiBrowserTest.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/VaadinBrowserFactory.java
Selenium 4 doesn't support PhantomJS anymore.
> fix: Remove PhantomJS support

- vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java
Related to: https://github.com/vaadin/flow-components/issues/7312
> feat: Add hover() to TestBenchElement

- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasClearButton.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/HasValidation.java
- vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
- vaadin-testbench-core/src/test/java/com/vaadin/testbench/TestBenchElementTest.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
- vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
> Cherry pick from 9.4 to 8.3

- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/grid/BasicGridTesterTest.java
- vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/grid/BasicGridView.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/grid/GridTester.java
Fixes #1966 
Analogous to what I did in UI Unit Test for Vaadin 8
https://github.com/vaadin/uiunittest/blob/master/src/main/java/com/vaadin/testbench/uiunittest/testers/GridTester.java#L72
> fix: Attach rendered component

- vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/CommercialTestWrappers.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java
> feat: introduce separate testers factory class for commercial components

- vaadin-testbench-integration-tests-junit5/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/ElementQueryView.java
- vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/internal/BasicUtilsTest.kt
- vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/internal/ElementUtilsTest.kt
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuTester.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/grid/GridTester.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/virtuallist/VirtualListTester.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/ComponentTester.java
- vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/LitRendererTestUtil.java
- vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/BasicUtils.kt
- vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/Shortcuts.kt
- vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/BasicUtilsTest.kt
- vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/ElementUtilsTest.kt
Fix testbench elemental usage
to match jackson usage in flow
> fix: Switch from elemental to Jackson
