vaadin/testbench

testbench-integration-tests/src/main/java/com/vaadin/testUI/TwinColSelectUI.java
testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/listselect/ListSelectOptionClickIT.java
testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/twincolselect/TwinColSelectUIIT.java
vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TwinColSelectElement.java

Fixes #810
Also removed check for multiple selection as it's always multiple
Added regression test for TwinColSelect and ListSelect
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/824)

Empty before selecting to prevent invalid options moving

---

testbench-integration-tests/src/main/java/com/vaadin/testUI/SelectByText.java
testbench-integration-tests/src/test/java/com/vaadin/tests/testbenchapi/components/combobox/SelectByTextIT.java
vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/ComboBoxElement.java

If a ComboBox contains
* Option 100
* Option 10
* Option 1
Then selectByText("Option 1") should select the last, not the first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/833)

Fix ComboBox.selectByText when multiple options match the text

---

vaadin-testbench-api/pom.xml
vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java
vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java
vaadin-testbench-core/pom.xml
vaadin-testbench-core/src/main/java/com/vaadin/testbench/annotations/BrowserFactory.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelTest.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/TestBenchBrowserFactory.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/SetupDriver.java

Set encoding for testbench api
Remove unmappable characted
Fix incorrect annotation in TableElement javadoc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/834)

Fix javadoc generation with java 8

---

documentation/creatingtests/testbench-screenshots.asciidoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/838)

Fix broken class names in documentation

---

vaadin-testbench-api/pom.xml
vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/GridElement.java
vaadin-testbench-api/src/main/java/com/vaadin/testbench/elements/TableElement.java
vaadin-testbench-core/pom.xml
vaadin-testbench-core/src/main/java/com/vaadin/testbench/annotations/BrowserFactory.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelTest.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/TestBenchBrowserFactory.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/SetupDriver.java

* Fix javadoc errors
* Remove unmappable character from javadoc
* Remove unmappable characters from javadoc from core
* Define encoding for testbench-api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/841)

Fix javadoc generation with java 8 (#834)

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java

From 4.2
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/849)

Take UnsupportedCommandException into account for element screenshots

---

pom.xml
testbench-integration-tests/src/main/java/com/vaadin/testUI/CheckBoxGroupSetValue.java
testbench-integration-tests/src/main/java/com/vaadin/testUI/DateFieldPopupSetValue.java
testbench-integration-tests/src/main/java/com/vaadin/testUI/ListSelectOptionClick.java
testbench-integration-tests/src/main/java/com/vaadin/testUI/NativeSelectSetValue.java
testbench-integration-tests/src/main/java/com/vaadin/testUI/RadioButtonGroupSetValue.java
testbench-integration-tests/src/main/java/com/vaadin/testUI/TwinColSelectUI.java
testbench-integration-tests/src/main/java/com/vaadin/tests/AbstractTestUI.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/858)

Update to 8.0.0.beta1

---

documentation/testbench-quickstart.asciidoc
documentation/testbench-tutorial.asciidoc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/863)

Add note about FF Actions API to docs, closes #TB-86

---

documentation/testbench-quickstart.asciidoc
documentation/testbench-tutorial.asciidoc

Different versions of FF have different problems,
with GeckoDriver. Basically non of the FF versions works with
Selenium 3. This is mentioned in docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/868)

Add info to docs, that FF is not supoorted.

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/tools/CvalChecker.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/tools/LicenseChecker.java
vaadin-testbench-core/src/main/resources/com/vaadin/testbench/tools/CvalChecker.properties
vaadin-testbench-core/src/test/java/com/vaadin/testbench/licensechecker/LicenseCheckerTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/tools/CvalCheckerTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/878)

Show better error message when license checking fails

---

documentation/creatingtests/testbench-special.asciidoc
vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/ExecuteJavascriptIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/883)

Add helper for executing JavaScript

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/TestBenchElementIT.java

If a property is set using one type and retrieved as another type, it is converted automatically according to JavaScript conversion rules
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/920)

Add helpers for getting and setting element properties

---

pom.xml
testbench-integration-tests/pom.xml
vaadin-testbench-api/pom.xml
vaadin-testbench-assembly/pom.xml
vaadin-testbench-core/pom.xml
vaadin-testbench-standalone/pom.xml
vaadin-testbench/pom.xml

[partially adopted from #926]
In distribution management: http://vaadin.com/nexus/ -> https://tools.vaadin.com/nexus/
In repositories: http://vaadin.com/nexus/content/repositories/vaadin-addons -> https://maven.vaadin.com/vaadin-addons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/929)

update Vaadin Nexus urls to the latest version

---

pom.xml
vaadin-testbench-assembly/pom.xml
vaadin-testbench-core/pom.xml
vaadin-testbench-integration-tests/pom.xml
vaadin-testbench-standalone/pom.xml
vaadin-testbench/pom.xml

In distribution management: http://vaadin.com/nexus/ -> https://tools.vaadin.com/nexus/
In repositories: http://vaadin.com/nexus/content/repositories/vaadin-addons -> https://maven.vaadin.com/vaadin-addons
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/930)

update Vaadin Nexus urls to the latest version (#929)

---

pom.xml
testbench-integration-tests/pom.xml
vaadin-testbench-api/pom.xml
vaadin-testbench-assembly/pom.xml
vaadin-testbench-core/pom.xml
vaadin-testbench-standalone/pom.xml
vaadin-testbench/pom.xml

Right now SSL is causing peer not authenticated on certificate validation and preventing deployment.
Updated distributionManagement and repositories to match other projects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/946)

Prevent issue with certificate validation

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchDriverProxy.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/TestBenchDriverTest.java

Fixes #945
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/949)

Avoid an infinite loop when trying to find the innermost driver (#937)

---

vaadin-testbench-integration-tests/.gitignore
vaadin-testbench-integration-tests/pom.xml
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java

Locally you can define credentials in vaadin-testbench-integration-tests/local.properties as e.g.
```
sauce.user=myusername
sauce.sauceAccessKey=myaccesskey
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/938)

Use system properties for Saucelabs credentials 

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
vaadin-testbench-core/src/main/resources/com/vaadin/testbench/testbench.properties

This is a back-port of #961
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/962)

Add a runtime check that the expected Selenium version is found

---

vaadin-testbench-integration-tests/pom.xml
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/PrivateTB3Configuration.java

Pass a unique value (the maven build timestamp) as a tunnel id to the sauce connect plugin to ensure two builds started from two machines around the same time would not interfere with one another.
+ switch the flow dependency from SNAPSHOT to a specific version
fixes #959
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/965)

add unique Sauce Connect tunnel ID for each build

---

vaadin-testbench/pom.xml

The current release build in TC runs `mvn clean install deploy -Prelease` which triggers deployment twice. This change removes the 'deploy' goal from the 'release' profile so that deployment happens only once.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/972)

do not run the 'deploy' maven goal twice in release builds

---

vaadin-testbench-integration-tests/src/main/java/com/vaadin/testUI/SVGView.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/SVGIT.java
vaadin-testbench/src/main/java/com/vaadin/testbench/TestBenchElement.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/981)

Use JS click() instead of a simulated mouse click to avoid 'element is not clickable at point'

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchElement.java

Some Safari web driver versions always fails on element.isDisplayed...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/987)

Do not fail if scrollIntoView fails

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java

Fixes #989
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/990)

Fix ElementQuery for built-in elements or elements without a shadow root

---

vaadin-testbench-core/src/main/resources/com/vaadin/testbench/cyclic-object-workaround.js

Webcomponentsjs 1.1.1 sets an `X` property also..
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1042)

Yey, more Firefox 59 workarounds

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java

Recorder was dropped in 4.0 in favor of ElementQuery and TestBench section in the debug window
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1048)

Remove mention of deprecated recorder

---

vaadin-testbench-core/src/main/resources/com/vaadin/testbench/cyclic-object-workaround.js

Also consider protected properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1050)

Make CyclicObjectWorkaround specific for firefox

---

vaadin-testbench-integration-tests/pom.xml

Incorrect range in polymer webjar resolves to webcomponentsjs 2.0.0.beta2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1057)

Use fixed version of webcomponentsjs

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommands.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/commands/TestBenchCommandExecutorTest.java

This patch adds an API to change the used ReferenceNameGenerator to a custom one.
Fixes #1060
Fixes #1059
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1062)

Allow customising ReferenceNameGenerator

---

documentation/testbench-advanced-testing-concepts.asciidoc

Usage of xpath is limited now due to shadow dom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1065)

Don't encourage xpath in docs

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchDriverProxy.java

- Change JS logic to accumulate all elements found by Vaadin clients instead of returning only for the first client
Fixes #756
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1067)

Return all elements found by selector

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchDriverProxy.java

Last change was returning null if list of elements was empty which potentially changes the contract of returning an empty list when no element is found with given selector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1069)

Always return a list on TestBenchDriverProxy#executeSearch

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchDriverProxy.java

Change JS logic to accumulate all elements found by Vaadin clients instead of returning only for the first client
Fixes #756
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1071)

 Return all elements found by selector in all Vaadin clients

---

vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/SVGIT.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1088)

Skip SVG click on Safari 11 in integration test

---

documentation/bestpractices/testbench-bdd.asciidoc
documentation/creatingtests/testbench-selectors.asciidoc
documentation/creatingtests/testbench-special.asciidoc

All links pointing to the `master` branch of https://github.com/vaadin/testbench-demo, should point to the `8.0` branch (because `master` is Vaadin 10).
Fixes #1098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1099)

update docs to link to Vaadin 8-based testbench-demo

---

documentation/testbench-ci-server.asciidoc

Changed "Prevoiusly" to "Previously". Should be self explanatory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1101)

Fix typo in note about PhantomJS

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/ElementQuery.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/ElementQueryTest.java

This breaking API change was unintended and needs to be fixed before final release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1189)

Revert change from org.openqa.selenium.NoSuchElementException to java.util.NoSuchElementException

---

documentation/testbench-screenshots.asciidoc

Parameters.setCaptureScreenshotOnFailure(true) is deprecated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1185)

remove the deprecated method from code example

---

vaadin-testbench-bom/pom.xml
vaadin-testbench-core/src/main/java/com/vaadin/testbench/configuration/TestConfiguration.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/configuration/SampleTestConfiguration.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/configuration/additionaltargetconfiguration/AdditionalTestConfiguration.java

. Remove old test-data module dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1215)

Provide a default implementation of getContainerInfo

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/Parameters.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/LocalDriver.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/ParametersTest.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1234)

Allow running in headless mode using -Dcom.vaadin.testbench.Parameters.headless=true

---

documentation/testbench-advanced-testing-concepts.asciidoc
documentation/testbench-bdd.asciidoc
documentation/testbench-ci-server.asciidoc
documentation/testbench-creating-tests.asciidoc
documentation/testbench-getting-started.asciidoc
documentation/testbench-low-level-element-interactions.asciidoc
documentation/testbench-maintainable-tests-using-page-objects.asciidoc
documentation/testbench-making-tests-reliable.asciidoc
documentation/testbench-overview.asciidoc
documentation/testbench-own-grid.asciidoc
documentation/testbench-running-test-on-multiple-browsers.asciidoc
documentation/testbench-running-with-maven.asciidoc
documentation/testbench-screenshots.asciidoc

Fixes #1249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/testbench/1251)

Use standard AsciiDoc syntax for source code blocks

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/commands/TestBenchCommandExecutorTest.java

Cache elementScreenshotSupport per browser

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/commands/TestBenchCommandExecutorTest.java

* Cache elementScreenshotSupport per browser
* Make browsersWithoutElementScreenshot threadsafe
Fixes #1261

Cache elementScreenshotSupport per browser (#1264)

---

vaadin-testbench-core/pom.xml

Related with https://github.com/vaadin/flow/issues/10115

fix: support jdk 16 by aligning bytebuddy version in flow

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/ScreenshotOnFailureRule.java

If you set up the driver lifecycle incorrectly, the screenshot on failure rule can be called after somebody called `driver.quit()`. In this case you do not want the test to fail because of `org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?` rather you want to see the real exception causing the failure

Log warning instead of fail test if driver is already closed

---

vaadin-testbench-core/pom.xml

Configured kotlin-maven-plugin to allow compilation of Kotlin source code along with Java sources.
Replaced maven-javadoc-plugin with dokka-maven-plugin in core module to generate Javadocs also for Kotlin classes.
Attached kotlin source files to sources jar.
Fixes #1328

chore: Added support for Kotlin sources

---

vaadin-testbench-core/pom.xml

maven javadocs plugin fails when Kotlin source code is referenced
in Java documentation.
Maven javadocs plugin can be skipped because javadocs are generated
by dokka plugin, bound to package phase and activated by relase
profile or by setting testbench.javadocs system property.

chore: skip javadocs plugin in core module

---

pom.xml
vaadin-testbench-bom/pom.xml
vaadin-testbench-core/pom.xml
vaadin-testbench-integration-tests/pom.xml

Set the version to be 8.1-SNAPSHOT as there is no reason to update the major.

chore: set snapshot version to 8.1-SNAPSHOT

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java

The component query API that allows to scan the UI or a subtree for components matching given predicates,
and provides component wrappers for found elements.
Part of #1338

feat: added component query api

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-core/src/test/java/com/vaadin/flow/component/button/ButtonWrapTest.java
vaadin-testbench-core/src/test/java/com/vaadin/flow/component/notification/NotificationWrapTest.java
vaadin-testbench-core/src/test/java/com/vaadin/flow/component/textfield/TextFieldWrapTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentWrapTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/WrapperResolutionTest.java

To be consistent with TestBench, `select` is now `$`,
`selectFromCurrenView` is `$view` and current `$` becomes `wrap`.
Fixes #1378

refactor!: renamed $ and select methods

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java

Added helpers to verify the size of the search results:
exact size, in a range, min and max
Part of #1370

feat: Added component query helpers for expected result size

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java

ComponentQuery terminal operators returns wrappers and components for
the exactly generic type. This is a little bit annoying on consumer perspective
when the component is generic itself.
For example with `GridWrap<Grid<Bean>,Bean> grid_ = $(Grid.class).first()`
compiler complains about Grid not being a Grid<Bean>.
This patch uses wildcards and explicit casts on terminal operators, to
make client API more friendly, so that
`GridWrap<Grid<Bean>,Bean> grid_ = $(Grid.class).first()`
works without need for casts.

chore: Make ComponentQuery generics friendly

---

vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/BasicGridView.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/BasicGridWrapTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnit4BaseClassTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnitBaseClassTest.java

Make component view not register at
startup so it will not break scan all.

fix: BasicGridView is not available in scan all

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/UIUnit4Test.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/UIUnitTest.java
vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/MockVaadin.kt
vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockVaadinHelper.kt
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/TestCustomInstantiatorFactory.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnit4BaseClassTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnitBaseClassTest.java

Unit tests may need to provide custom implementations for Flow services
discovered through Lookup, such as a custom InstantiatorFactory.
This changes allows to provide custom services overriding base test
initVaadinEnvironment method and calling super implementation with
classes to be initialized during setup.

feat: Allow providing custom service implementations for Lookup

---

vaadin-testbench-unit/pom.xml
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/TreeOnFailureExtension.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/UIUnit4Test.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/UIUnitTest.java
vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/BasicUtils.kt
vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTree.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/LocatorTest.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTreeTest.kt

For Junit5 add `@ExtendWith(TreeOnFailureExtension.class)`
For Junit4 Override `printTree()` to return true
Fixes #1336

feat: add pretty print on assert fail

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/NonGenericTestWrap.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/TestComponentForConcreteWrapper.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/WrapperResolutionTest.java

Wrapper may not always be generic or they may have more than one generic type,
so we need to inspect class hierarchy to detect the correct component type
that matches the declaration in ComponentWrap.
Fixes #1387

feat: detect wrapper component type inspecting hierarchy

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java

Shortcut for `!all.isEmpty()`
Fixes #1382

feat: Added exists terminal operator to ComponentQuery

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentWrap.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/SpringUIUnit4Test.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/SpringUIUnitTest.java
vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockedUI.kt
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/ComponentWrapTest.java

An set modal component now gets a
detach listener that does a roundtrip
to propagate the modality change.
Fixes #1349

feat: removing modal component creates roundtrip

---

vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/textfield/TextFieldWrap.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/textfield/TextFieldWrapTest.java

Clears the text field setting the correct empty value.
Throws if clear button is not visible or component is not usable.
Fixes #1423

feat: Added clear to TextFieldWrap

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ReferenceNameGenerator.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/screenshot/ReferenceNameGeneratorTest.java

fix: Do not use unix name for linux screenshots (CP: 8.0)

---

vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/upload/UploadWrap.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/upload/UploadView.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/upload/UploadWrapTest.java

Allows to simulate upload of single e multiple files, abort and failure.
Part of #1371

feat: Added wrapper for Upload component

---

vaadin-testbench-bom/pom.xml

Drop the test scope in bom
for unit module as it makes
it not be brought in as a transitive
dependency with the core module

fix: Remove scope from unit module

---

vaadin-testbench-integration-tests/pom.xml

Use 9.0-snapshot of Flow instead of a
release version that is broken
due to npm package updates

chore: use flow 9.0-SNAPSHOT

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java

Throw an exception for all navigations
which do not result in the expected view.
Print to systrem err the stackTrace for
MockInternalServerError view.

fix: Better exception for failing navigation

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ElementConditions.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/ElementConditionsTest.java

Html component stores text content in innerHTML property.
This change fixes the `withTextContainig` helper, so that
the input string is searched against the normalized content
of innerHTML property value.

fix: support text containing predicate for Html components

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java

The signature with a fixed String and then the varargs
does not provide a good DX in IDEs

refactor: use only varargs for withClassName and withoutClassName

---

vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/grid/GridWrap.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/GetTextCellRendererTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/grid/RendererGridView.java

Currently for columns with component renderer, getCellText returns
a textual representation of the component object, not what may be displayed
on the screen.
With this change the method returns the concatenation of text node the
component is made up.
Fixes #1468

chore: Made GridWrap.getCellText return visible text for component renderers

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/UIUnit4Test.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/UIUnitTest.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/UIUnitTestSetupException.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnit4BaseClassTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnitBaseClassTest.java

The most used method of base test class now checks that
the UI is present and throw an exception if it is not.
Fixes #1475

feat: fail with informative message when Vaadin env is not set up correctly

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentQuery.java
vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/ComponentTester.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/login/LoginFormTesterTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/flow/component/login/LoginOverlayTesterTest.java
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java

Currently ComponentQuery can return either test wrappers or component.
With this change the results will be only components.
Developer will then wrap the components by their own when they need to
interact it them.
Fixes #1487

refactor!: ComponentQuery returns only components

---

vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/Routes.kt
vaadin-testbench-unit/src/test/java/com/vaadin/testbench/unit/UIUnitNavigationTest.java
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/RoutesTest.kt

MockRouteNotFoundError was used to rethrow a more detailed exception on
navigation errors.
Now it does not throws but holds a reference to the exception and adds
informative message as Div text content.
Fixes #1447

refactor!: MockRouteNotFoundError does not rethrow exception anymore

---

vaadin-testbench-unit/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java

for component with generic type like Grid, ComboBox, etc.
Components returned by ComponentQuery are erased, so instead
of Grid<Bean> we get a simple Grid.
With the new methods we can infer the value type again when
getting the tester instance, by providing the value type class.
Fixes #1401

feat: Added tester factory method to improve type inference

---

vaadin-testbench-unit/src/main/kotlin/com/vaadin/testbench/unit/internal/Routes.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/RoutesTest.kt

Making MockRouteNotFoundError extending RouteNotFoundError and
annotating it with `@DefaultErrorHandler` won't make Vaadin apps fail at
startup when vaadin-testbench-unit incidentally is on classpath and
would also preserve the output from the out-of-the-box handler, so
testbench tests checking for it would continue to work without any
change.

refactor: make MockRouteNotFoundError extend RouteNotFoundError

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/BrowserUtil.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/DefaultBrowserFactory.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelRunner.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ReferenceNameGenerator.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/BrowserUtilTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/DefaultBrowserConfigurationTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/JobNameCapabilitiesTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/screenshot/ReferenceNameGeneratorTest.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/TB6TestBrowserFactory.java
vaadin-testbench-unit/src/main/java/com/vaadin/flow/component/html/testbench/DescriptionListTester.java

If a test is using custom desired capabilities, these need to be updated to the W3C standard.
Saucelabs options need to be set using the `SauceLabsIntegration.setSauceLabsOption` and not directly on the `DesiredCapability` object.
Fixes #1429

fix!: Use W3C capabilities

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/BrowserUtil.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/parallel/ParallelHubTest.java
vaadin-testbench-integration-tests/pom.xml

Read tunnel identifier from sauce.tunnelId property or SAUCE_TUNNEL_ID env variable
Note that this changes the default URL used for Sauce Labs from http://localhost:4445/wd/hub to the recommended https://ondemand.saucelabs.com/wd/hub. If you have an existing setup relying on the old Maven plugin, you might need to override `getHubUrl` to return the old URL

fix!: Make Saucelabs integration use what Saucelabs recommends

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java

Different users might have different saucelabs endpoints.
Now it's possible to configure it by using the `sauce.hubUrl` system property or the `SAUCE_HUB_URL` environment variable.
Possible values are available in https://docs.saucelabs.com/basics/data-center-endpoints/#data-center-endpoints
fixes: #1511

feat: allow setting sauce hub url with property or env

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/Parameters.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/RemoteDriver.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/ParametersTest.java

This allows you to increase the timeout e.g. when using Saucelabs so that tests wait for a session to become available instead of timing out and causing test failures

feat: Support setting the read timeout for remote web drivers

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/RemoteDriver.java

RemoteDriverBuilder apparently causes problems with Selenoid for unknown reasons

Use a custom CommandExecutor instead of RemoteDriverBuilder

---

vaadin-testbench-core/pom.xml
vaadin-testbench-core/src/main/java/com/vaadin/testbench/Parameters.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/ScreenshotOnFailureRule.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/ScreenshotComparator.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelRunner.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/ParallelTest.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/SauceLabsIntegration.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/RemoteDriver.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ImageComparison.java
vaadin-testbench-core/src/main/java/com/vaadin/testbench/screenshot/ScreenShotFailureReporter.java

Cherry picks the following log related changes:
* a261ab85 - chore: Log using logger instead of system.out
* b28709d2 - fix: Log using logger instead of system.err (#1505)
* 26301926 - chore: Use slf4j like the rest of the platform (#1313)

chore: Use slf4j like the rest of the platform

---

vaadin-testbench-integration-tests/pom.xml
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/TB6TestBrowserFactory.java

currently SC start and stop is done outside of maven lifecycle and tunnel ID is defined as env variable or system property

test: remove sauce.options definition from pom

---

pom.xml

Update OpenJDK to 17 due to upcoming Jakarta EE 9 update

chore: update maven.compiler.source/.target to 17

---

vaadin-testbench-integration-tests/pom.xml

currently SC start and stop is done outside of maven lifecycle and tunnel ID is defined as env variable or system property

test: remove sauce.options definition from pom (#1544)

---

vaadin-testbench-core/pom.xml

fix: support jdk 16 and align bytebuddy version with flow (#1287)
fix: Update to latest Javassist for Java 16 compat (#1288)

Java 16 cherry-picks (#1287) (#1288)

---

pom.xml

Because commons-fileupload2 is now available as a part of Flow

chore: Remove apache commons snap repo

---

vaadin-testbench-core-junit5/pom.xml
vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/AbstractBrowserTestBase.java
vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/BrowserTestBase.java
vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/BrowserTestClass.java
vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/browser/BrowserExtension.java
vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/browser/BrowserTestInfo.java
vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/browser/BrowserTestClassTest.java
vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/browser/ExtensionWithBrowserConfigurationInParametersTest.java
vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/browser/ExtensionWithBrowserConfigurationTest.java
vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/browser/ExtensionWithoutBrowserConfigurationTest.java
vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/browser/JobNameCapabilitiesTest.java
vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/AbstractBrowserTB9Test.java
vaadin-testbench-integration-tests-junit5/vite.generated.ts
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/textfield/TextAreaTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/textfield/TextFieldTesterTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/grid/GridTester.java
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/component/Grid.kt

Helper methods used in flow-tests have been moved to testbench. Injection of `WebDriver` and `Capabilities` have been replaced with single `BrowserTestInfo` with extended properties.

feat!: Extend BrowserTestBase with common methods from flow-tests

---

vaadin-testbench-unit-shared/pom.xml

Polymer templates module has been excluded from platform in V24, so we need to add it manually.

chore: Added polymer template module explicitly

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/textfield/TextAreaTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/textfield/NumberFieldTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/textfield/TextAreaTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/textfield/TextFieldTester.java

Adapt TextFieldTester to new TextField hierarchy.
Temporary fix for TextAreaTester test, setting required with setRequiredIndicatorVisible

test: adapt Testers to component changes

---

vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/IPAddressTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/IPAddressTest.java

Not only "172.16", but a wider portion of the "172" address range, is designated for private use.
172.16.0.0/12 IP addresses: 172.16.0.0 – 172.31.255.255

test: fixed 172 private ip address range

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/ComponentQueryTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/textfield/TextFieldTester.java

related changes https://github.com/vaadin/flow-components/commit/8b6c3f1050081244ec1393232ff9acbbb031b91e

chore: fix compilation after textfield renaming

---

vaadin-testbench-bom/pom.xml

this should be picked to 8.2 and 8.1 which are using selenium 4.0+, as this module has been introduced since Selenium 4.0

chore: Add selenium-chromium-driver to testbench bom

---

vaadin-testbench-bom/pom.xml
vaadin-testbench-shared/pom.xml
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBench.java

Uses the new JDK 11 based HTTP client which does not have a problem with sending extra Origin-headers

fix: Make Chrome 111 work

---

vaadin-testbench-bom/pom.xml
vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBench.java

Uses the new JDK 11 based HTTP client which does not have a problem with sending extra Origin-headers

fix: Make Chrome 111 work (CP: 8.2)

---

pom.xml

I just saw this along the way I worked in this project.
This is a fix from <currentYear>2022</currentYear> to <currentYear>2023</currentYear>. This is used in
header.txt which is used in the license-maven-plugin. Not sure if we can have a problem because of 2022 legally, but better to fix this I feel.

fix: current year from 2022 -> 2023 (used in licenses) 

---

pom.xml
vaadin-testbench-core-junit5/pom.xml
vaadin-testbench-core/pom.xml
vaadin-testbench-integration-tests-junit5/pom.xml
vaadin-testbench-integration-tests/pom.xml
vaadin-testbench-shared/pom.xml
vaadin-testbench-unit-shared/pom.xml

also make the dependency available for updating via `maven-versions-plugin:use-latest-versions`

chore: update license-checker version to 1.12.3

---

vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java

At least fixes a navigation test in Flow

fix: Ignore spurious chromedriver error

---

vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/details/DetailsTester.java

It looks like since https://github.com/vaadin/flow-components/pull/4909 the `Details` component now properly dispatches an opened changed event when changing the `opened` property, so the faked event from `DetailsTester` can be removed.

fix: remove duplicate opened changed event

---

vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/AbstractBrowserTestBase.java

E.g. SeleniumHubPageObjectIT in this project is run without TestBench being properly initialized

chore: Ensure TestBench is initialized for SeleniumJupiter tests

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/RetryRule.java

Currently, RetryRule show details only of the last caught exception, but this one may not be the real reason of the test failure. This change prints the stack trace of all caught expections when debug level for RetryRule is at least 'debug', helping the develper to detect the real cause of the test failure.
Fixes #1527

feat: log all exceptions caught by RetryRule

---

vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/browser/BrowserExtension.java
vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/browser/BrowserHubTest.java
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/Parameters.java

In some scenarios it is not possible or hard to set a fixed port for the selenium hub. For example if the hub is run dynamically in the CI pipeline through testcontainers.
This change allows to specify a different port from the default 4444 and thus, in the docker case, does not force to map the hub port fixed to 4444 on the host, which may lead to conflicting port mappings.
Fixes: https://github.com/vaadin/testbench/issues/1657
Rebases https://github.com/vaadin/testbench/pull/1658 on main branch.
Many thanks to @ErrorProne for contribution!

feat: Add variable hub port capabilities

---

vaadin-testbench-core-junit5/pom.xml

Remove dependencies that are
not needed from the junit5 core
package.

chore: remove unnecessary commons dependencies

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/accordion/AccordionTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/details/DetailsTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/dialog/DialogTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/listbox/MultiSelectListBoxTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/menubar/MenuBarTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/messages/MessageInputTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/notification/NotificationTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/textfield/NumberFieldTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/textfield/TextAreaTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/timepicker/TimePickerTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/upload/UploadTesterTest.java

Some of the UI Unit Test tests classes still contain the old `Wrap` suffix in the name, and the class does not match the containing file name.
This change renames the test classes to replace the `Wrap` part with the correct `Tester` word.

test: rename test classes to match containing file

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/sidenav/SideNavTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/sidenav/SideNavView.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/sidenav/TargetView.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/sidenav/SideNavTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/ComponentTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/ComponentUtils.kt

Also refactors ComponentTester to expose some utility method to subclasses.
Part of #1635

feat: add tester for SideNav component

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/tabs/TabsTesterTest.java

The first parameter of the assertion should be the expected object, the second one the actual value.
In the current code, they are inverted.
This change fixes the parameters order.

test: fix assertion paramters order

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/tabs/TabsTesterTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/tabs/TabSheetTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/tabs/TabsTester.java

The Tabs tester index base operation currently does not care about tabs visibility, thus not correctly reflecting the action in the browser. If there are three tabs, but the one in the middle is hidden, operation for index 2 should effectively act on the third registered tab. This change fixes fetching the tab by index by filtering out hidden tabs.

fix: make tabs tester index operations work on visible tabs

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/grid/GridTesterSortTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/grid/GridTester.java

GridTester.sortByColumn(): consider the value of MultiSortPriority as well.
Fixes #1695

fix: GridTester.sortByColumn(): consider the value of MultiSortPriority as well.

---

vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/WaitForVaadinIT.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/WaitForVaadinIT.java
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java

Adds a new hook in waitForVaadin while loop for tests. New tests verifies that waiting stops properly after client flag `devServerIsNotLoaded` is changed or client's `isActive()` return value changes.
Related to: #1705

test: add tests for waitForVaadin

---

vaadin-testbench-integration-tests-junit5/pom.xml
vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/PerformanceIT.java
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/commands/TestBenchCommandExecutor.java

Adds checks to ensure that client has `poll` and `getProfilingData` functions before calling them.
Fixes Jetty configuration in `pom.xml` to comply with Jetty version 11.
Fixes adn re-enabled `PerformanceIT`.
Fixes #1316
Fixes #1704

Fix performance data fetching

---

vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/mocks/MockSpringServlet.java
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/component/Grid.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/ComponentUtils.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/Routes.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/TestingLifecycleHook.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/Utils.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockVaadinHelper.kt

Currently classes are loaded with Class.forName, that uses the classloader from the calling class. However, this might not work on all environments because of different class loading setup (e.g in Quarkus testing). This change uses the current thread context class loader as fallback when Class.forName is not able to load a class.
Fixes vaadin/quarkus#139
Part of #1655

fix: fallback to context classloader when loading class

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/BrowserUtil.java

The newer Chrome versions report different browser name depending on being headless mode or not. Both are prefixed with "chrome", hence altering checking from equals to startsWith.
fixes #1741

chore: Fix isChrome to work with newer Chrome versions

---

pom.xml
vaadin-testbench-bom/pom.xml
vaadin-testbench-unit-quarkus/pom.xml
vaadin-testbench-unit-quarkus/src/main/java/com/vaadin/testbench/unit/quarkus/QuarkusUIUnitTest.java
vaadin-testbench-unit-quarkus/src/main/java/com/vaadin/testbench/unit/quarkus/mocks/MockQuarkusServlet.java
vaadin-testbench-unit-quarkus/src/main/java/com/vaadin/testbench/unit/quarkus/mocks/MockQuarkusServletService.java
vaadin-testbench-unit-quarkus/src/test/java/com/example/base/DummyService.java
vaadin-testbench-unit-quarkus/src/test/java/com/example/base/HelloWorldView.java
vaadin-testbench-unit-quarkus/src/test/java/com/example/base/WelcomeView.java
vaadin-testbench-unit-quarkus/src/test/java/com/vaadin/testbench/unit/quarkus/QuarkusUIUnitBaseClassTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java

Adds a base class for UI Unit testing on Quarkus.
Provides mocks for QuarkusVaadinServlet and QuarkusVaadinServletService integrated with Quarkus CDI.
Fixes vaadin/quarkus#140
Part of #1655

feat: add UI Unit test base class for Quarkus

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/html/testbench/AnchorTesterTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/html/testbench/AnchorTester.java

Adds a `download` method to `AnchorTester` that allows testing that downloads for an anchor work properly.

feat: add download method to AnchorTester

---

vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/ElementQueryTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/ElementQueryTest.java
vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/ElementQueryIT.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/ElementQueryIT.java
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/ElementQuery.java

Refactored name of "xContaining" attribute selector methods to "xContainingToken".
Added true "xContaining" attribute selector methods that match on substrings instead of on tokens.
Added remaining attribute matching operators and a corresponding selector method to utilize them. Refactored existing attribute-based selector methods to use this method.
Fixes #1554

feat: rework "containing" selectors via addition of remaining attribute operators

---

pom.xml
vaadin-testbench-core-junit5/pom.xml
vaadin-testbench-core/pom.xml
vaadin-testbench-shared/pom.xml

This upgrade is needed to resolve the failure in dependency convergence check in Hilla.

chore: upgrade javassist to 3.30.2-GA

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/html/testbench/AnchorTesterTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/html/testbench/AnchorTester.java

Added support for query parameters to AnchorTester.
Fixes #1811

Added support for query parameters to AnchorTester.

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/parallel/setup/LocalDriver.java

The search engine selection dialogue doesn't affect testing, or show up in screenshots, but it makes local debugging difficult by hiding content visually.

fix: Disable Chrome's search engine selection dialogue in LocalDriver

---

vaadin-testbench-shared/src/main/java/com/vaadin/testbench/parallel/setup/LocalDriver.java

Fixes https://github.com/vaadin/testbench/issues/1817

fix: disable chrome search engine selection

---

vaadin-testbench-unit-quarkus/pom.xml

Aligns version with vaadin-quarkys add-on.

chore: bump Quarkus to 3.2

---

vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/internal/AsyncTest.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/AsyncTest.kt

When executing access enqueued command, Flow clears all thread locals in CurrentInstance (vaadin/flow#20255), so VaadinRequest and VaadinResponse will never be available.

test: ensure Vaadin request and response are not available in access() commands

---

pom.xml
vaadin-testbench-core-junit5/pom.xml
vaadin-testbench-integration-tests-junit5/pom.xml

in the Junit5 IT test module, all test classes are queued in saucelab, which leads to 'flaky' test result with timeout. 
so adding the `forkCount` setting seems make it more stable.

upgrade failsafe/surefire plugin, selenium-jupiter version. 

---

vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/internal/LocatorTest.kt
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/datepicker/DatePickerTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/timepicker/TimePickerTester.java
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/LocatorTest.kt

Validation API of Date/Time/DateTime picker has been changed since Vaadin 24.5, and the UI Unit testers are failing with recent Vaadin version. This change makes the testers compatible with all Vaadin 24 series.
Fixes #1840

fix: fix date/time/datetime picker tester validation

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SecurityTestConfig.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/SpringUnitSecurityTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/testbench/unit/UIUnitBaseClassTest.java
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockInstantiator.kt

fix: make MenuAccessControl availalble in mocking environment

---

vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/mocks/MockHttpSessionTest.kt
vaadin-testbench-unit-shared/pom.xml
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockContext.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockHttpSession.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockRequest.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockResponse.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/mocks/MockHttpSessionTest.kt

- upgrade servlet-api dependency
- remove deprecated apis/overwrites
reference servlet-api docs https://tomcat.apache.org/tomcat-10.0-doc/servletapi/jakarta/servlet/ServletContext.html and https://tomcat.apache.org/tomcat-11.0-doc/servletapi/jakarta/servlet/ServletContext.html

chore: upgrade servlet-api to 6.0.0

---

pom.xml
vaadin-testbench-unit-junit5/pom.xml
vaadin-testbench-unit-quarkus/pom.xml
vaadin-testbench-unit-shared/pom.xml
vaadin-testbench-unit/pom.xml

- upgrade the outdated spring.version
- use spring-boot-dependencies bom to simplify the spring versions
- remove spring.version and spring.security.version usage

chore: simplify spring dependency management

---

vaadin-testbench-core-junit5/src/main/java/com/vaadin/testbench/AbstractBrowserTestBase.java
vaadin-testbench-core-junit5/src/test/java/com/vaadin/testbench/TestBenchElementTest.java
vaadin-testbench-core/src/test/java/com/vaadin/testbench/TestBenchElementTest.java
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java

Fixes https://github.com/vaadin/testbench/issues/1843

chore: deprecate getAttribute

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/AbstractTargetView.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/RouterLinkQueryParameterTargetView.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/RouterLinkRouteParameterTargetView.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/RouterLinkStaticTargetView.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/RouterLinkTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/RouterLinkUrlParameterTargetView.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/routerlink/RouterLinkView.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/routerlink/RouterLinkTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/TesterWrappers.java

Adds missing `ComponentTester` for `RouterLink`. (Attempting to use `AnchorTester` in its place results in an error due to `Anchor` and `RouterLink` being different `Components`.
Tester methods include
- `getHref`
- `getPath`
- `getQueryParameters`
- `getRoute`
- `click`
Fixes #1805

Added tester for RouterLink.

---

vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/TestUtils.kt
vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/internal/BasicUtilsTest.kt
vaadin-testbench-unit-junit5/src/test/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTreeTest.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/TestUtils.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/BasicUtilsTest.kt
vaadin-testbench-unit/src/test/kotlin/com/vaadin/testbench/unit/internal/PrettyPrintTreeTest.kt

In flow-components 24.8 a new property has been added to some field components causing test failures because assertions are based on the textual representation of the component and the introduced attribute is not expected. This change updates the assertion to use a regular expression to check only the relevant part of the component representation.

chore: use regex to assert component state

---

vaadin-testbench-integration-tests-junit5/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/BasicElementIT.java
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java

Mere JS call to click does not focus the element. Real life action of clicking element always focuses it. This is important if in the test story it is important that clicking Button e.g. blurs TextField, which in turn triggers value change in TextField.

fix: Focus on click

---

vaadin-testbench-core/src/main/java/com/vaadin/testbench/TestBenchTestCase.java
vaadin-testbench-integration-tests/src/test/java/com/vaadin/tests/elements/AbstractTB5Test.java

Selenium 4 uses Durations where Selenium 3 used long timeouts. Deprecate the old method (but keep it for backward compatibility), and switch to using the Selenium 4 style with Durations by default.

feat: Switch to use a new Selenium 4 style waitUntil method (V8)

---

vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchElement.java

Selenium reverted the deprecation for getAttribute method after community feedback. This change removes the deprecation also from TestbenchElement class.

chore: reverted deprecation notice for getAttribute

---

vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/dialog/DialogTesterTest.java
vaadin-testbench-unit-junit5/src/test/java/com/vaadin/flow/component/notification/NotificationTesterTest.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialogTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenuTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/dialog/DialogTester.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/flow/component/notification/NotificationTester.java
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/internal/ComponentUtils.kt
vaadin-testbench-unit-shared/src/main/kotlin/com/vaadin/testbench/unit/mocks/MockedUI.kt

In v25 overlay components such as Dialog, ConfirmDialog, etc. have been refactored to wait for the `closed` event before removing themselves from the UI, which is required to wait for the overlays closing animation for finish.
This updates `MockedUI` so that it registers a listener on overlay components that automatically fires the event when the `opened` property changes to `false`, which simulates what would happen when using the component in a browser.
- Refactoring

refactor: auto-remove overlay components with closed event

---

pom.xml
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBench.java
vaadin-testbench-shared/src/main/java/com/vaadin/testbench/TestBenchVersion.java
vaadin-testbench-unit-shared/src/main/java/com/vaadin/testbench/unit/BaseUIUnitTest.java

Updates to latest LC 2.0 and uses pre-trial for TestBench so that it can be used once the pre-trial is started by user.

chore: Update license-checker version to 2.0.0-beta4
